"""baseline schema

Revision ID: 20f6acf94ce2
Revises:
Create Date: 2026-08-23 16:34:49.790600
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from narrate.db.triggers import APPEND_ONLY_TRIGGERS

revision: str = "20f6acf94ce2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ledger_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("script_id", sa.Integer(), nullable=True),
        sa.Column("chunk_id", sa.Integer(), nullable=True),
        sa.Column("take_id", sa.Integer(), nullable=True),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("billed_chars", sa.Integer(), nullable=False),
        sa.Column("rate_usd_per_1k", sa.Float(), nullable=False),
        sa.Column("rate_card_version", sa.String(length=32), nullable=False),
        sa.Column("cost_micros", sa.Integer(), nullable=False),
        sa.Column("credits", sa.Float(), nullable=False),
        sa.Column("cost_source", sa.String(length=16), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ledger_entry", schema=None) as batch_op:
        batch_op.create_index("ix_ledger_project", ["project_id"], unique=False)
        batch_op.create_index("ix_ledger_ts", ["ts"], unique=False)

    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("voice_id", sa.String(length=64), nullable=True),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("settings_json", sa.Text(), nullable=False),
        sa.Column("prefix_tags", sa.Text(), nullable=False),
        sa.Column("monthly_cap_micros", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "reconciliation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("window_start", sa.DateTime(), nullable=False),
        sa.Column("window_end", sa.DateTime(), nullable=False),
        sa.Column("local_chars", sa.Integer(), nullable=False),
        sa.Column("provider_chars", sa.Integer(), nullable=False),
        sa.Column("local_micros", sa.Integer(), nullable=False),
        sa.Column("drift_pct", sa.Float(), nullable=False),
        sa.Column("within_threshold", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "effect",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=96), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("loop", sa.Boolean(), nullable=False),
        sa.Column("prompt_influence", sa.Float(), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("output_format", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("asset_path", sa.Text(), nullable=True),
        sa.Column("actual_duration_s", sa.Float(), nullable=True),
        sa.Column("observed_cost", sa.Integer(), nullable=True),
        sa.Column("rate_usd_per_min", sa.Float(), nullable=False),
        sa.Column("rate_card_version", sa.String(length=32), nullable=False),
        sa.Column("cost_micros", sa.Integer(), nullable=False),
        sa.Column("credits", sa.Float(), nullable=False),
        sa.Column("cost_source", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("error_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("effect", schema=None) as batch_op:
        batch_op.create_index("ix_effect_idempotency", ["idempotency_key"], unique=False)

    op.create_table(
        "script",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("source_path", sa.Text(), nullable=True),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=True),
        sa.Column("voice_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chunk",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("script_id", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=True),
        sa.Column("target_start_s", sa.Float(), nullable=True),
        sa.Column("prefix_tags", sa.Text(), nullable=True),
        sa.Column("voice_id", sa.String(length=64), nullable=True),
        sa.Column("model_id", sa.String(length=64), nullable=True),
        sa.Column("settings_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["script_id"], ["script.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("script_id", "ordinal", name="uq_chunk_order"),
    )
    op.create_table(
        "effect_slot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("script_id", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("at_chunk_ordinal", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("loop", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("effect_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["effect_id"], ["effect.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["script_id"], ["script.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("effect_slot", schema=None) as batch_op:
        batch_op.create_index("ix_effect_slot_script", ["script_id"], unique=False)

    op.create_table(
        "export",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("script_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("fmt", sa.String(length=16), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=False),
        sa.Column("cut_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("gap_seconds", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["script_id"], ["script.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("script_id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("estimate_micros", sa.Integer(), nullable=False),
        sa.Column("spent_micros", sa.Integer(), nullable=False),
        sa.Column("max_spend_micros", sa.Integer(), nullable=True),
        sa.Column("concurrency", sa.Integer(), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["script_id"], ["script.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "take",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("voice_id", sa.String(length=64), nullable=False),
        sa.Column("settings_json", sa.Text(), nullable=False),
        sa.Column("output_format", sa.String(length=32), nullable=False),
        sa.Column("submitted_text", sa.Text(), nullable=False),
        sa.Column("submitted_chars", sa.Integer(), nullable=False),
        sa.Column("billed_chars", sa.Integer(), nullable=False),
        sa.Column("cost_source", sa.String(length=16), nullable=False),
        sa.Column("rate_usd_per_1k", sa.Float(), nullable=False),
        sa.Column("rate_card_version", sa.String(length=32), nullable=False),
        sa.Column("cost_micros", sa.Integer(), nullable=False),
        sa.Column("credits", sa.Float(), nullable=False),
        sa.Column("asset_path", sa.Text(), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("error_json", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["chunk_id"], ["chunk.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("take", schema=None) as batch_op:
        batch_op.create_index("ix_take_chunk", ["chunk_id"], unique=False)
        batch_op.create_index("ix_take_idempotency", ["idempotency_key"], unique=False)

    op.create_table(
        "cut",
        sa.Column("chunk_id", sa.Integer(), nullable=False),
        sa.Column("script_id", sa.Integer(), nullable=False),
        sa.Column("take_id", sa.Integer(), nullable=False),
        sa.Column("selected_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["chunk_id"], ["chunk.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["script_id"], ["script.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["take_id"], ["take.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("chunk_id"),
    )
    # ### end Alembic commands ###

    # The ledger's immutability is part of the schema, not a convention
    # for callers to remember (PRD §7).
    for statement in APPEND_ONLY_TRIGGERS:
        op.execute(statement)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cut")
    with op.batch_alter_table("take", schema=None) as batch_op:
        batch_op.drop_index("ix_take_idempotency")
        batch_op.drop_index("ix_take_chunk")

    op.drop_table("take")
    op.drop_table("run")
    op.drop_table("export")
    with op.batch_alter_table("effect_slot", schema=None) as batch_op:
        batch_op.drop_index("ix_effect_slot_script")

    op.drop_table("effect_slot")
    op.drop_table("chunk")
    op.drop_table("script")
    with op.batch_alter_table("effect", schema=None) as batch_op:
        batch_op.drop_index("ix_effect_idempotency")

    op.drop_table("effect")
    op.drop_table("reconciliation")
    op.drop_table("project")
    with op.batch_alter_table("ledger_entry", schema=None) as batch_op:
        batch_op.drop_index("ix_ledger_ts")
        batch_op.drop_index("ix_ledger_project")

    op.drop_table("ledger_entry")
    # ### end Alembic commands ###
