"""ledger units provider nullable project

Revision ID: 75bbda75ce01
Revises: 20f6acf94ce2
Create Date: 2026-08-23 17:55:06.953823
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "75bbda75ce01"
down_revision: str | None = "20f6acf94ce2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Let the ledger express seconds and tokens, not only characters.

    Existing rows are all ElevenLabs speech billed per character, so they are
    backfilled from `billed_chars`. `cost_micros` and `credits` are never
    touched: a migration that shifted a historical figure would be worse than
    no migration at all, since reconciliation replays this table.

    The new columns carry a `server_default` because the table already has
    rows — adding a NOT NULL column without one fails on a populated table.
    """
    with op.batch_alter_table("ledger_entry", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("provider", sa.String(length=24), nullable=False, server_default="elevenlabs")
        )
        batch_op.add_column(sa.Column("units", sa.Float(), nullable=False, server_default="0"))
        batch_op.add_column(
            sa.Column(
                "unit_kind", sa.String(length=16), nullable=False, server_default="characters"
            )
        )
        # An account-level charge belongs to no project. Previously every entry
        # was forced to name one.
        batch_op.alter_column("project_id", existing_type=sa.INTEGER(), nullable=True)

    op.execute("UPDATE ledger_entry SET units = billed_chars WHERE units = 0")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ledger_entry", schema=None) as batch_op:
        batch_op.alter_column("project_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("unit_kind")
        batch_op.drop_column("units")
        batch_op.drop_column("provider")

    # ### end Alembic commands ###
