"""Producing a finished episode in one operation.

Speech and effects are generated by two existing runs —
[`runner.generate`](runner.py) and [`effects.generate_slots`](effects.py) — and
this module orchestrates them rather than merging them. The speech runner is
already long and entirely speech-specific; the effects runner owns cue reuse.
Neither should learn about the other.

**The one thing that had to change is the budget gate.** `runner.generate`
projected its monthly-cap check from the pending chunks alone. In a combined
run that sees roughly half the spend, so an episode could pass the cap on
narration and then take the month past it on effects. The projection is
computed here, over both phases, and checked once before either starts.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field

from sqlalchemy import Engine

from narrate import ledger
from narrate.db.models import Project, Script
from narrate.db.session import session_scope
from narrate.effects import EffectOutcome, EffectRates, generate_slots
from narrate.provider.base import SFXProvider, TTSProvider
from narrate.registry import Registry
from narrate.runner import RunReport, generate
from narrate.settings import Settings


@dataclass
class Projection:
    """What a production is about to cost, split by what it buys."""

    speech_micros: int = 0
    effect_micros: int = 0
    chunks: int = 0
    chars: int = 0
    effects: int = 0
    effect_seconds: float = 0.0

    @property
    def total_micros(self) -> int:
        return self.speech_micros + self.effect_micros

    @property
    def is_empty(self) -> bool:
        return self.chunks == 0 and self.effects == 0


@dataclass
class ProductionReport:
    """The outcome of one production, across both phases."""

    speech: RunReport | None = None
    effects: list[EffectOutcome] = field(default_factory=list)
    projection: Projection = field(default_factory=Projection)
    dry_run: bool = True
    blocked: bool = False
    stopped_reason: str | None = None

    @property
    def spent_micros(self) -> int:
        speech = self.speech.spent_micros if self.speech else 0
        return speech + sum(o.cost_micros for o in self.effects)

    @property
    def effects_generated(self) -> int:
        return sum(1 for o in self.effects if o.status == "generated")

    @property
    def effects_reused(self) -> int:
        return sum(1 for o in self.effects if o.status == "reused")

    @property
    def effects_failed(self) -> list[EffectOutcome]:
        return [o for o in self.effects if o.status == "failed"]


def project(
    engine: Engine,
    script_id: int,
    registry: Registry,
    *,
    with_effects: bool = True,
    only: list[int] | None = None,
    force: bool = False,
    settings: Settings | None = None,
) -> Projection:
    """Price the work still to do, across both phases.

    Delegates to [`ledger.outstanding`](ledger.py), which already counts
    chunks with no selected take and accepted effect slots with no audio, and
    prices both from the rate card. Computing it a second way here would be a
    second answer to the same question.
    """
    rates = EffectRates.load()
    with session_scope(engine) as session:
        # Strict: this figure is what a run is confirmed and held to.
        todo = ledger.outstanding(
            session, script_id, registry, only=only, force=force, settings=settings, strict=True
        )

    effect_micros = rates.cost_micros(todo.effect_seconds) if with_effects else 0
    return Projection(
        # `outstanding` returns one figure for both; the effect half is
        # recomputed from its seconds so the split can be shown.
        speech_micros=todo.cost_micros - rates.cost_micros(todo.effect_seconds),
        effect_micros=effect_micros,
        chunks=todo.chunks,
        chars=todo.chars,
        effects=todo.effects if with_effects else 0,
        effect_seconds=todo.effect_seconds if with_effects else 0.0,
    )


async def produce(
    engine: Engine,
    script_id: int,
    tts: TTSProvider,
    sfx: SFXProvider,
    registry: Registry,
    settings: Settings,
    *,
    with_effects: bool = True,
    only: list[int] | None = None,
    dry_run: bool = True,
    force: bool = False,
    max_spend_micros: int | None = None,
    concurrency: int | None = None,
    override_cap: bool = False,
    on_event: Callable[[str], None] | None = None,
) -> ProductionReport:
    """Generate the speech, then the accepted effect cues, as one operation."""

    def note(message: str) -> None:
        if on_event:
            on_event(message)

    projection = project(
        engine,
        script_id,
        registry,
        with_effects=with_effects,
        only=only,
        force=force,
        settings=settings,
    )
    report = ProductionReport(dry_run=dry_run, projection=projection)

    # The cap is checked here, once, against both phases. Passing the effect
    # figure down to the speech runner keeps a single gate rather than two that
    # each see part of the picture.
    speech = await generate(
        engine,
        script_id,
        tts,
        registry,
        settings,
        only=only,
        dry_run=dry_run,
        force=force,
        max_spend_micros=max_spend_micros,
        concurrency=concurrency,
        override_cap=override_cap,
        extra_projected_micros=projection.effect_micros,
        on_event=on_event,
    )
    report.speech = speech

    if speech.stopped_reason == "monthly_cap":
        # Blocked before anything was sent. Neither phase runs — spending on
        # cues for an episode whose narration was refused would be worse than
        # spending on nothing.
        report.blocked = True
        report.stopped_reason = "monthly_cap"
        return report

    report.stopped_reason = speech.stopped_reason

    if not with_effects:
        return report

    # Effects run even when the speech phase had failures: a cue does not
    # depend on the narration around it, and is useful on its own.
    if speech.failed:
        note(
            f"{len(speech.failed)} chunk(s) failed; generating the effect cues anyway "
            "— they do not depend on the speech."
        )

    report.effects = await generate_slots(
        engine,
        script_id,
        sfx,
        settings,
        dry_run=dry_run,
        on_event=on_event,
    )
    return report


def describe(projection: Projection, rates: EffectRates | None = None) -> list[str]:
    """The pre-flight split, as lines. Shared by the CLI and the API."""
    from narrate.money import fmt_usd

    card = rates or EffectRates.load()
    lines: list[str] = []
    if projection.chunks:
        lines.append(
            f"  narration   {projection.chunks} chunk(s)  {projection.chars:,} chars"
            f"   {fmt_usd(projection.speech_micros, 4):>10}"
        )
    if projection.effects:
        lines.append(
            f"  effects     {projection.effects} cue(s)  "
            f"{projection.effect_seconds:g}s"
            f"   {fmt_usd(projection.effect_micros, 4):>10}"
            f"   [dim]at ${card.usd_per_minute:.2f}/min[/dim]"
        )
    return lines


def script_project_id(engine: Engine, script_id: int) -> int | None:
    with session_scope(engine) as session:
        script = session.get(Script, script_id)
        if script is None:
            return None
        project_row = session.get(Project, script.project_id)
        return project_row.id if project_row else None
